name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish Blazor App
        run: dotnet publish BlazorApp1/BlazorApp1.csproj -c Release

      - name: Copy index.html to 404.html
        run: cp BlazorApp1/bin/Release/net8.0/publish/wwwroot/index.html BlazorApp1/bin/Release/net8.0/publish/wwwroot/404.html

      - name: Add .nojekyll file
        run: touch BlazorApp1/bin/Release/net8.0/publish/wwwroot/.nojekyll

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: BlazorApp1/bin/Release/net8.0/publish/wwwroot

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
